config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recuriements
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
     #get 'home/index'
       get 'home/about'
     root to: "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recuriement.rb
class Recuriement < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/controllers/recuriements_controller.rb
class RecuriementsController < ApplicationController
  before_action :set_recuriement, only: %i[ show edit update destroy ]

  # GET /recuriements or /recuriements.json
  def index
    @recuriements = Recuriement.all
  end

  # GET /recuriements/1 or /recuriements/1.json
  def show
  end

  # GET /recuriements/new
  def new
    @recuriement = Recuriement.new
  end

  # GET /recuriements/1/edit
  def edit
  end

  # POST /recuriements or /recuriements.json
  def create
    @recuriement = Recuriement.new(recuriement_params)

    respond_to do |format|
      if @recuriement.save
        format.html { redirect_to recuriement_url(@recuriement), notice: "Recuriement was successfully created." }
        format.json { render :show, status: :created, location: @recuriement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recuriement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recuriements/1 or /recuriements/1.json
  def update
    respond_to do |format|
      if @recuriement.update(recuriement_params)
        format.html { redirect_to recuriement_url(@recuriement), notice: "Recuriement was successfully updated." }
        format.json { render :show, status: :ok, location: @recuriement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recuriement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recuriements/1 or /recuriements/1.json
  def destroy
    @recuriement.destroy

    respond_to do |format|
      format.html { redirect_to recuriements_url, notice: "Recuriement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recuriement
      @recuriement = Recuriement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recuriement_params
      params.require(:recuriement).permit(:first_name, :last_name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recuriements_helper.rb
module RecuriementsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Recuirement', root_path, Class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      	<%= link_to "About", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Recuirement", recuriements_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Recuirement", new_recuriement_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Signin",  new_user_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Signup",  new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Signout",  destroy_user_session_path, class:"nav-link" %>
      </li>
     
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About..</h1>

app/views/home/index.html.erb
<h1>WELCOME TO THE RECURIMENT HOME PAGE.</h1>
Thanks for visiting my Recuirment page. 
<%= current_user.email %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <%= notice %>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Recuriment</title>
  </head>
  <body>
    <br/>
    <%= render 'home/header' %>
    <div class="container"> 
       
      <% if notice %>
       <%= render 'layouts/alerts' %>
       <% end %>
    <%= yield %>

  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>




<!DOCTYPE html>
<html>
  <head>
    <title>Recuriment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <body>
    
  </body>
</html>

app/views/recuriements/_form.html.erb
<%= form_with(model: recuriement) do |form| %>
  <% if recuriement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recuriement.errors.count, "error") %> prohibited this recuriement from being saved:</h2>

      <ul>
        <% recuriement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"email@gmail.com" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"your mobile number" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/recuriements/_recuriement.html.erb
<div id="<%= dom_id recuriement %>">
  <p>
    <strong>First name:</strong>
    <%= recuriement.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= recuriement.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= recuriement.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= recuriement.phone %>
  </p>

</div>

app/views/recuriements/edit.html.erb
<h1>Edit Profile</h1>
<br></br>

<%= render "form", recuriement: @recuriement %>

<br>

<div>
  <%= link_to "Show", @recuriement, class:"btn btn-primary" %> |
  <%= link_to "Back", recuriements_path, class:"btn btn-dark" %>
</div>

app/views/recuriements/index.html.erb
<table class="table table-striped table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>FirstName</th>
      <th>LastName</th>
      <th>Email</th>
      <th>PhoneNo</th>
    </tr>
  </thead>

  <tbody>
    <% @recuriements.each do|recuriement| %>
    <tr>
      <td><%= recuriement.first_name %></td>
      <td><%= recuriement.last_name %></td>
      <td><%=recuriement.email %></td>
      <td><%=recuriement.phone %></td>

      <td><%= link_to 'show', recuriement, class:"btn btn-primary" %></td>

      <% if current_user %>

        <td><%= link_to 'Edit', edit_recuriement_path(recuriement), class:"btn btn-info" %></td>
        <td><%= button_to 'Destroy', recuriement, method: :delete, class:"btn btn-dark" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New recuriement", new_recuriement_path, class:"btn btn-info" %>

app/views/recuriements/new.html.erb
<h1>Add New recuriement</h1>
<br></br> 
<%= render "form", recuriement: @recuriement %>

<br>

<div>
  <%= link_to "Back", recuriements_path, class:"btn btn-primary" %>
</div>

app/views/recuriements/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @recuriement.first_name %>
    <%= @recuriement.last_name %>
  </h1>
  <p class="lead">
    <%= @recuriement.email %> |
    <%= @recuriement.phone %>
  </p>
  <hr class="my-4">
  <%= link_to "Edit", edit_recuriement_path(@recuriement), class:"btn btn-info" %> 

  <%= link_to "Back", recuriements_path, class:"btn btn-info" %>
  <br></br>
  <%= button_to "Destroy this recuriement", @recuriement, method: :delete, class:"btn btn-danger" %>
</div>